backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

display_url: https://jasherio.netlify.com

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/data/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Cover", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "config"
    label: "Config"
    files:
      - file: "src/data/config.json"
        label: "Site"
        name: "site"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Alternate, name: alternate, widget: string, required: false}
          - {label: Description, name: description, widget: string}
          - {label: Copyright, name: copyright, widget: string}
          # - {label: Logo, name: logo, widget: image, required: false}
          - {label: URL, name: url, widget: string}
          - {label: RSS, name: rss, widget: string}
          - {label: GitHub, name: github, widget: string, required: false}
          - {label: LinkedIn, name: linkedin, widget: string, required: false}
          - {label: Twitch, name: twitch, widget: string, required: false}
          - {label: Twitter, name: twitter, widget: string, required: false}
          - {label: Google Analytics ID, name: googleAnalyticsId, widget: string, required: false}
          - {label: Google Tag Manager ID, name: googleTagManagerId, widget: string, required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/data/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
